version: "3.8"
services:
    web:
        image: frz09/fun-facts
        ports:
            - 80:80
        networks:
            - app-net
        depends_on:
            - db
    db:
        image: frz09/fun-facts
        networks:
            - app-net
        environment:
            MYSQL_ROOT_PASSWORD: "ExamPa$$w0rd"
networks:
    app-network:
